services:
  - docker

before_install:
  - docker build -t tsugden/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tsugden/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket-name: "elasticbeanstalk-us-east-2-449895140964"
  bucket-path: "docker-react"
  on:
    branch: master
  access_key_id: $aws_access_key_id
  secret_access_key:
    secure: $aws_secret_access_key

language: generic
